services:
  mongodb:
    image: mongo:7
    container_name: ara-assessment-mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ara_assessment
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
